# Generated by Django 5.2.16 on 2026-07-31 18:27

import django.db.models.deletion
import transactions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(default=transactions.models.generate_tx_id, editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('buyer_email', models.EmailField(blank=True, help_text='Used if buyer not registered', max_length=254)),
                ('seller_email', models.EmailField(blank=True, help_text='Used if seller not registered', max_length=254)),
                ('initiator_role', models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Broker', 'Broker')], default='Buyer', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(choices=[('USD', 'USD — US Dollar ($)'), ('EUR', 'EUR — Euro (€)'), ('GBP', 'GBP — British Pound (£)'), ('CAD', 'CAD — Canadian Dollar'), ('AUD', 'AUD — Australian Dollar')], default='USD', max_length=3)),
                ('category', models.CharField(choices=[('Domain Names', 'Domain Names'), ('Motor Vehicles', 'Motor Vehicles (Cars, Boats, Aircraft)'), ('Estate & Real Estate', 'Estate & Real Estate'), ('General Merchandise', 'General Merchandise'), ('Jewelry & Watches', 'Jewelry & Watches'), ('Antiques & Collectibles', 'Antiques & Collectibles'), ('Milestone Services', 'Milestone Services & Contracts'), ('IPv4 Addresses', 'IPv4 Addresses'), ('Software & Digital Assets', 'Software & Digital Assets')], default='General Merchandise', max_length=60)),
                ('inspection_period', models.PositiveIntegerField(default=2, help_text='Inspection period in days')),
                ('status', models.CharField(choices=[('Draft', 'Draft — Awaiting Funding'), ('Funded', 'Funded — Payment Held'), ('In Inspection', 'In Inspection Period'), ('In Progress', 'In Progress'), ('Completed', 'Completed — Funds Released'), ('Cancelled', 'Cancelled'), ('Disputed', 'Disputed — Under Review')], default='Draft', max_length=20)),
                ('is_partnered', models.BooleanField(default=False)),
                ('escrow_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_transactions', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartneredPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_email', models.EmailField(max_length=254)),
                ('split_type', models.CharField(choices=[('50_50', '50% / 50% Equal Split'), ('partner_full', 'Partner Pays Full Remaining Balance'), ('custom', 'Custom Contribution Amount')], default='50_50', max_length=20)),
                ('partner_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('partner_status', models.CharField(choices=[('pending', 'Payment Link Sent — Awaiting Partner'), ('paid', 'Partner Payment Received'), ('expired', 'Link Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_token', models.CharField(default=transactions.models.generate_partner_token, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partnered_payment', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Partnered Payment',
                'verbose_name_plural': 'Partnered Payments',
            },
        ),
        migrations.CreateModel(
            name='TransactionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Transaction Created'), ('funded', 'Payment Funded'), ('inspection_start', 'Inspection Period Started'), ('inspection_end', 'Inspection Period Ended'), ('partner_invited', 'Partner Payment Invited'), ('partner_paid', 'Partner Payment Received'), ('approved', 'Buyer Approved Release'), ('completed', 'Transaction Completed'), ('cancelled', 'Transaction Cancelled'), ('disputed', 'Dispute Raised'), ('resolved', 'Dispute Resolved'), ('admin_note', 'Admin Note Added')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Activity Log Entry',
                'verbose_name_plural': 'Activity Log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TransactionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='tx_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='transactions.transaction')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Document',
                'verbose_name_plural': 'Transaction Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
