# Generated by Django 5.2.16 on 2026-08-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='partner_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='transaction',
            name='partner_receipt',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='primary_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='transaction',
            name='primary_receipt',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft — Awaiting Funding'), ('Pending Verification', 'Pending Verification — Receipt Uploaded'), ('Funded', 'Funded — Payment Confirmed'), ('In Inspection', 'In Inspection Period'), ('In Progress', 'In Progress'), ('Completed', 'Completed — Funds Released'), ('Cancelled', 'Cancelled'), ('Disputed', 'Disputed — Under Review')], default='Draft', max_length=20),
        ),
    ]
