# Generated by Django 5.2.16 on 2026-08-07 03:45

import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_partner_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_id',
            field=models.CharField(default=transactions.models.generate_tx_id, max_length=20, unique=True),
        ),
    ]
